# Generated by Django 4.1.7 on 2023-04-11 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_city_country_district_product_delete_productmodel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
