# Generated by Django 4.1.6 on 2023-02-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_productmodel_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='name',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='item_name',
            field=models.CharField(default='A', max_length=255),
            preserve_default=False,
        ),
    ]
