# Generated by Django 4.1.6 on 2023-02-24 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_productmodel_name_productmodel_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='item_name',
        ),
    ]
