# Generated by Django 4.1.6 on 2023-02-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_productmodel_item_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_category', models.CharField(max_length=100)),
                ('product_image', models.ImageField(upload_to='product_images')),
                ('product_price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='ProductModel',
        ),
    ]
