# Generated by Django 4.2 on 2023-05-04 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_image_mymodel_remove_district_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.mymodel'),
            preserve_default=False,
        ),
    ]
