# Generated by Django 4.2 on 2023-05-04 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
