# Generated by Django 4.2 on 2023-05-05 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
